<a href="https://colab.research.google.com/github/AnisaIntania/Desain-dan-Analisis-Algoritma/blob/main/DAA_Pertemuan_3_Anisa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Latihan 1: Buatlah list dengan nama “Mahasiswa” yang berisi nama, NIM, prodi, mata kuliah,tanggal hari ini, nama universitas**

In [ ]:
from datetime import date
tgl = date.today()
print(tgl)

import datetime as vDate
hari = vDate.date.day
tanggal = vDate.date.today()
print(hari)
print(tanggal)

Mahasiswa = ["Anisa Intania Putri",
             2024071010,
             "Informatika",
             "DAA",
              f"{tanggal.year}, {tanggal.month}, {tanggal.day}",
             "Universitas Pembangunan Jaya" ]
print(Mahasiswa)

2025-09-16
<attribute 'day' of 'datetime.date' objects>
2025-09-16
['Anisa Intania Putri', 2024071010, 'Informatika', 'DAA', '2025, 9, 16', 'Universitas Pembangunan Jaya']


**Contoh List index**

In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[1]

'Green'

**Latihan 2: Cetak NIM dengan
memanggil urutan
indeks dalam list
“Mahasiswa”!**

In [ ]:
#nim saja
print("NIM", Mahasiswa[1:2])

NIM [2024071010]


**Latihan 3: Cetak nama
universitas dengan
memanggil urutan
indeks dalam list
“Mahasiswa”!**

In [ ]:
print("Univ:", Mahasiswa[5])

Univ: Universitas Pembangunan Jaya


**Contoh List slicing**

In [ ]:
print("NIM", Mahasiswa[1:2])

NIM [2024071010]


In [ ]:
#prodi saja
print("Prodi", Mahasiswa[2:3])

Prodi ['Informatika']


In [ ]:
#nim dan prodi
print("NIM & Prodi", Mahasiswa[1:3])

NIM & Prodi [2024071010, 'Informatika']


In [ ]:
print("Mata Kuliah tanggal berapa? ", Mahasiswa[3:5])

Mata Kuliah tanggal berapa?  ['DAA', '2025, 9, 16']


In [ ]:
print("Nama Kampus ", Mahasiswa[5:6])

Nama Kampus  ['Universitas Pembangunan Jaya']


**Python bisa melakukan iterasi tiap elemen dalam list dengan for loop**

In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
  print(aColor + ' Square' )

Red Square
Green Square
Blue Square
Yellow Square


**Latihan 4: Cetak isi list
“Mahasiswa”,
tambahkan kata “UPJ”
di depan!**

In [ ]:
import datetime
tanggal = datetime.date.today()

Mahasiswa = ["Anisa Intania Putri",
             2024071010,
             "Informatika",
             "DAA",
             f"{tanggal.year}, {tanggal.month}, {tanggal.day}",
             "Universitas Pembangunan Jaya" ]

for mhs in Mahasiswa:
    print("UPJ " + str(mhs))

UPJ Anisa Intania Putri
UPJ 2024071010
UPJ Informatika
UPJ DAA
UPJ 2025, 9, 16
UPJ Universitas Pembangunan Jaya


**Contoh data tuples ()**

In [ ]:
#tuples pake kurung biasa bukan kurung siku
bin_colors=('Red', 'Green', 'Blue', 'Yellow')
bin_colors[1]

'Green'

**Latihan 5: Susun Tuple bernama
“UPJ”, isi dengan
Universitas, Pembangunan,
Jaya**

In [ ]:
#tuples upj
upj = ("Universitas", "Pembangunan", "Jaya")
print(upj)

('Universitas', 'Pembangunan', 'Jaya')


**Latihan 6: Buat tuple bersarang
bernama “nested_tuple”**

In [ ]:
nested_tuple = (100, (200, 400, 600), 300, (400, 800))
print(nested_tuple)

**Contoh Data Dictionary**

In [ ]:
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


**Untuk mengambil nilai dari key ada 2 cara, bisa pakai `get()` atau langsung indeks key**

In [ ]:
bin_colors.get('approved_color')

'Green'

In [ ]:
bin_colors['approved_color']

'Green'

**Memperbarui nilai dengan key**

In [ ]:
bin_colors['approved_color'] = "Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


**Latihan 7: Membuat dictionary dan pemanggilan menggunakan get()**

In [ ]:
#dictionary: membuat struktur data yang berisikan keys dan values
mhs = {
    #keys : values
    "Nama" : "Anisa Intania Putri",
    "NIM" : "2024071010",
    "Prodi" : "Informatika",
    "Universitas" : "UPJ"
}

print(mhs)

{'Nama': 'Anisa Intania Putri', 'NIM': '2024071010', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


**Contoh data sets. Sets (menampilkan data yg unique) = kumpulan
elemen yang dapat berbeda jenis. Kalo ada data inputan yang sama persis (duplikat) akan diabaikan.**

In [ ]:
green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [ ]:
green = {'grass', 'leaves', 'leaves'} #kalo ada data yang sama maka akan diabaikan
print(green)

**Latihan 8: menyusun red dan yellow sehingga
mendapatkan hasil gabungan dan irisan seperti dicontoh**

In [ ]:
green = {'leaves', 'fire hydrant', 'rose', 'blood'}
red = {'leaves', 'fire hydrant', 'dandelions'}

print("green|red", green|red) # gabungan (union)
print("green&red", green&red) # irisan (intersection)

green|red {'blood', 'dandelions', 'fire hydrant', 'rose', 'leaves'}
green&red {'leaves', 'fire hydrant'}


**Contoh DataFrame**

In [ ]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]
])

df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [ ]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [ ]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [ ]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

**Latihan 9: Membuat data frame sesuai dengan contoh di ppt**

In [ ]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Informatika', 50, 30, 20],
    ['2', 'Sistem Informasi', 55, 30, 25],
    ['3', 'Teknik Sipil', 40, 30, 10]])

df.columns = ['No', 'Prodi', 'Mahasiswa', 'Laki-Laki', 'Perempuan']
(df)

No             Prodi  Mahasiswa  Laki-Laki  Perempuan
0  1       Informatika         50         30         20
1  2  Sistem Informasi         55         30         25
2  3      Teknik Sipil         40         30         10

In [ ]:
#yg siswa lk nya dia tas 50 dan pr di atas 20
print("\nMahasiswa > 50:")
print(df[df['Mahasiswa'] > 50])


Mahasiswa > 50:
  No             Prodi  Mahasiswa  Laki-Laki  Perempuan
1  2  Sistem Informasi         55         30         25


In [ ]:
# Prodi dengan mahasiswa laki-laki lebih banyak dari perempuan
print("\nLaki-Laki > Perempuan:")
print(df[df['Laki-Laki'] > df['Perempuan']])


Laki-Laki > Perempuan:
  No             Prodi  Mahasiswa  Laki-Laki  Perempuan
0  1       Informatika         50         30         20
1  2  Sistem Informasi         55         30         25
2  3      Teknik Sipil         40         30         10


In [ ]:
# Prodi dengan jumlah mahasiswa < 60 dan jumlah perempuan >= 25
print("\nMahasiswa < 60 DAN Perempuan >= 25:")
print(df[(df['Mahasiswa'] < 60) & (df['Perempuan'] >= 25)])


Mahasiswa < 60 DAN Perempuan >= 25:
  No             Prodi  Mahasiswa  Laki-Laki  Perempuan
1  2  Sistem Informasi         55         30         25


In [ ]:
# Prodi dengan mahasiswa >= 40 ATAU laki-laki < 20
print("\nMahasiswa >= 40 ATAU Laki-Laki < 20:")
print(df[(df['Mahasiswa'] >= 40) | (df['Laki-Laki'] < 20)])


Mahasiswa >= 40 ATAU Laki-Laki < 20:
  No             Prodi  Mahasiswa  Laki-Laki  Perempuan
0  1       Informatika         50         30         20
1  2  Sistem Informasi         55         30         25
2  3      Teknik Sipil         40         30         10


**Contoh data matrix**

In [ ]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
print(type(myMatrix))

<class 'numpy.ndarray'>


**Latihan 10: Membuat matrix dengan nilai yang sudah ditentukan di ppt**

In [ ]:
import numpy as np
A = np.array([[ 100, 200, 300], [700, 600, 500], [900, 1000, 800 ]])
print(A)

#Transpos Matrix
transpos = A.T
print(" Transpos Matrix")
print(transpos)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
 Transpos Matrix
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


**Contoh data abstrak Vektor**

In [ ]:
myVektor = [22, 33, 44, 55]
print(myVektor)

[22, 33, 44, 55]


In [ ]:
print(type(myVektor))

<class 'list'>


In [ ]:
myVektor = np.array([22, 33, 44, 55])
print(myVektor)

[22 33 44 55]


In [ ]:
print(type(myVektor))

<class 'numpy.ndarray'>


**Contoh Stack**

In [ ]:
class Stack:
    def __init__(self):
        self.items = []

    def isEmpty(self):
        return self.items == []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.isEmpty():
            return self.items.pop()
        else:
            return "Stack is empty"

    def peek(self):
        if not self.isEmpty():
            return self.items[len(self.items) - 1]
        else:
            return "Stack is empty"

    def size(self):
        return len(self.items)


# -----------------------------
# Contoh penggunaan
stack = Stack()

stack.push("Red")
stack.push("Green")
stack.push("Blue")
stack.push("Yellow")

print("Isi stack:", stack.items)     # ['Red', 'Green', 'Blue', 'Yellow']
print("Pop:", stack.pop())           # Yellow
print("Peek:", stack.peek())         # Blue
print("Is Empty:", stack.isEmpty())  # False
print("Size:", stack.size())         # 3

Isi stack: ['Red', 'Green', 'Blue', 'Yellow']
Pop: Yellow
Peek: Blue
Is Empty: False
Size: 3


**Contoh Queue**

In [ ]:
class Queue(object):
    def __init__(self):
        self.items = []

    def isEmpty(self):
        return self.items == []

    def enqueue(self, item):
        self.items.insert(0, item)

    def dequeue(self):
        return self.items.pop()

    def size(self):
        return len(self.items)


# Contoh penggunaan
queue = Queue()

queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')

print("Ukuran queue:", queue.size())  # 4
print("Dequeue:", queue.dequeue())   # Red
print("Dequeue:", queue.dequeue())   # Green
print("Apakah kosong?", queue.isEmpty())  # False


Ukuran queue: 4
Dequeue: Red
Dequeue: Green
Apakah kosong? False
